<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-03 20:40

import django.db.models.deletion
=======
# Generated by Django 5.1.6 on 2025-02-09 13:40

>>>>>>> 0984425 (1-commit)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat', to='mein.group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=30, verbose_name='Famila')),
                ('yosh', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mein.group')),
            ],
        ),
        migrations.CreateModel(
            name='Belgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attended', models.BooleanField(default=False)),
                ('davomat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat_belgi', to='mein.davomat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_belgi', to='mein.student')),
            ],
            options={
                'unique_together': {('davomat', 'student')},
            },
        ),
=======
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
>>>>>>> 0984425 (1-commit)
    ]
